const languageCodes = [
	{ label: 'Arabic', value: 'ar' },
	{ label: 'English', value: 'en' },
	{ label: 'French', value: 'fr' },
	{ label: 'Spanish', value: 'es' },
	{ label: 'German', value: 'de' },
	{ label: 'Italian', value: 'it' },
	{ label: 'Japanese', value: 'ja' },
]

export const allLanguageCodes = [
	{ label: 'Abkhazian', value: 'ab' },
	{ label: 'Achinese', value: 'ace' },
	{ label: 'Acoli', value: 'ach' },
	{ label: 'Adangme', value: 'ada' },
	{ label: 'Adyghe', value: 'ady' },
	{ label: 'Afar', value: 'aa' },
	{ label: 'Afrihili', value: 'afh' },
	{ label: 'Afrikaans', value: 'af' },
	{ label: 'Aghem', value: 'agq' },
	{ label: 'Ainu', value: 'ain' },
	{ label: 'Akan', value: 'ak' },
	{ label: 'Akkadian', value: 'akk' },
	{ label: 'Akoose', value: 'bss' },
	{ label: 'Alabama', value: 'akz' },
	{ label: 'Albanian', value: 'sq' },
	{ label: 'Aleut', value: 'ale' },
	{ label: 'Algerian Arabic', value: 'arq' },
	{ label: 'American English', value: 'en_US' },
	{ label: 'American Sign Language', value: 'ase' },
	{ label: 'Amharic', value: 'am' },
	{ label: 'Ancient Egyptian', value: 'egy' },
	{ label: 'Ancient Greek', value: 'grc' },
	{ label: 'Angika', value: 'anp' },
	{ label: 'Ao Naga', value: 'njo' },
	{ label: 'Arabic', value: 'ar' },
	{ label: 'Aragonese', value: 'an' },
	{ label: 'Aramaic', value: 'arc' },
	{ label: 'Araona', value: 'aro' },
	{ label: 'Arapaho', value: 'arp' },
	{ label: 'Arawak', value: 'arw' },
	{ label: 'Armenian', value: 'hy' },
	{ label: 'Aromanian', value: 'rup' },
	{ label: 'Arpitan', value: 'frp' },
	{ label: 'Assamese', value: 'as' },
	{ label: 'Asturian', value: 'ast' },
	{ label: 'Asu', value: 'asa' },
	{ label: 'Atsam', value: 'cch' },
	{ label: 'Australian English', value: 'en_AU' },
	{ label: 'Austrian German', value: 'de_AT' },
	{ label: 'Avaric', value: 'av' },
	{ label: 'Avestan', value: 'ae' },
	{ label: 'Awadhi', value: 'awa' },
	{ label: 'Aymara', value: 'ay' },
	{ label: 'Azerbaijani', value: 'az' },
	{ label: 'Badaga', value: 'bfq' },
	{ label: 'Bafia', value: 'ksf' },
	{ label: 'Bafut', value: 'bfd' },
	{ label: 'Bakhtiari', value: 'bqi' },
	{ label: 'Balinese', value: 'ban' },
	{ label: 'Baluchi', value: 'bal' },
	{ label: 'Bambara', value: 'bm' },
	{ label: 'Bamun', value: 'bax' },
	{ label: 'Banjar', value: 'bjn' },
	{ label: 'Basaa', value: 'bas' },
	{ label: 'Bashkir', value: 'ba' },
	{ label: 'Basque', value: 'eu' },
	{ label: 'Batak Toba', value: 'bbc' },
	{ label: 'Bavarian', value: 'bar' },
	{ label: 'Beja', value: 'bej' },
	{ label: 'Belarusian', value: 'be' },
	{ label: 'Bemba', value: 'bem' },
	{ label: 'Bena', value: 'bez' },
	{ label: 'Bengali', value: 'bn' },
	{ label: 'Betawi', value: 'bew' },
	{ label: 'Bhojpuri', value: 'bho' },
	{ label: 'Bikol', value: 'bik' },
	{ label: 'Bini', value: 'bin' },
	{ label: 'Bishnupriya', value: 'bpy' },
	{ label: 'Bislama', value: 'bi' },
	{ label: 'Blin', value: 'byn' },
	{ label: 'Blissymbols', value: 'zbl' },
	{ label: 'Bodo', value: 'brx' },
	{ label: 'Bosnian', value: 'bs' },
	{ label: 'Brahui', value: 'brh' },
	{ label: 'Braj', value: 'bra' },
	{ label: 'Brazilian Portuguese', value: 'pt_BR' },
	{ label: 'Breton', value: 'br' },
	{ label: 'British English', value: 'en_GB' },
	{ label: 'Buginese', value: 'bug' },
	{ label: 'Bulgarian', value: 'bg' },
	{ label: 'Bulu', value: 'bum' },
	{ label: 'Buriat', value: 'bua' },
	{ label: 'Burmese', value: 'my' },
	{ label: 'Caddo', value: 'cad' },
	{ label: 'Cajun French', value: 'frc' },
	{ label: 'Canadian English', value: 'en_CA' },
	{ label: 'Canadian French', value: 'fr_CA' },
	{ label: 'Cantonese', value: 'yue' },
	{ label: 'Capiznon', value: 'cps' },
	{ label: 'Carib', value: 'car' },
	{ label: 'Catalan', value: 'ca' },
	{ label: 'Cayuga', value: 'cay' },
	{ label: 'Cebuano', value: 'ceb' },
	{ label: 'Central Atlas Tamazight', value: 'tzm' },
	{ label: 'Central Dusun', value: 'dtp' },
	{ label: 'Central Kurdish', value: 'ckb' },
	{ label: 'Central Yupik', value: 'esu' },
	{ label: 'Chadian Arabic', value: 'shu' },
	{ label: 'Chagatai', value: 'chg' },
	{ label: 'Chamorro', value: 'ch' },
	{ label: 'Chechen', value: 'ce' },
	{ label: 'Cherokee', value: 'chr' },
	{ label: 'Cheyenne', value: 'chy' },
	{ label: 'Chibcha', value: 'chb' },
	{ label: 'Chiga', value: 'cgg' },
	{ label: 'Chimborazo Highland Quichua', value: 'qug' },
	{ label: 'Chinese', value: 'zh' },
	{ label: 'Chinook Jargon', value: 'chn' },
	{ label: 'Chipewyan', value: 'chp' },
	{ label: 'Choctaw', value: 'cho' },
	{ label: 'Church Slavic', value: 'cu' },
	{ label: 'Chuukese', value: 'chk' },
	{ label: 'Chuvash', value: 'cv' },
	{ label: 'Classical Newari', value: 'nwc' },
	{ label: 'Classical Syriac', value: 'syc' },
	{ label: 'Colognian', value: 'ksh' },
	{ label: 'Comorian', value: 'swb' },
	{ label: 'Congo Swahili', value: 'swc' },
	{ label: 'Coptic', value: 'cop' },
	{ label: 'Cornish', value: 'kw' },
	{ label: 'Corsican', value: 'co' },
	{ label: 'Cree', value: 'cr' },
	{ label: 'Creek', value: 'mus' },
	{ label: 'Crimean Turkish', value: 'crh' },
	{ label: 'Croatian', value: 'hr' },
	{ label: 'Czech', value: 'cs' },
	{ label: 'Dakota', value: 'dak' },
	{ label: 'Danish', value: 'da' },
	{ label: 'Dargwa', value: 'dar' },
	{ label: 'Dazaga', value: 'dzg' },
	{ label: 'Delaware', value: 'del' },
	{ label: 'Dinka', value: 'din' },
	{ label: 'Divehi', value: 'dv' },
	{ label: 'Dogri', value: 'doi' },
	{ label: 'Dogrib', value: 'dgr' },
	{ label: 'Duala', value: 'dua' },
	{ label: 'Dutch', value: 'nl' },
	{ label: 'Dyula', value: 'dyu' },
	{ label: 'Dzongkha', value: 'dz' },
	{ label: 'Eastern Frisian', value: 'frs' },
	{ label: 'Efik', value: 'efi' },
	{ label: 'Egyptian Arabic', value: 'arz' },
	{ label: 'Ekajuk', value: 'eka' },
	{ label: 'Elamite', value: 'elx' },
	{ label: 'Embu', value: 'ebu' },
	{ label: 'Emilian', value: 'egl' },
	{ label: 'English', value: 'en' },
	{ label: 'Erzya', value: 'myv' },
	{ label: 'Esperanto', value: 'eo' },
	{ label: 'Estonian', value: 'et' },
	{ label: 'European Portuguese', value: 'pt_PT' },
	{ label: 'European Spanish', value: 'es_ES' },
	{ label: 'Ewe', value: 'ee' },
	{ label: 'Ewondo', value: 'ewo' },
	{ label: 'Extremaduran', value: 'ext' },
	{ label: 'Fang', value: 'fan' },
	{ label: 'Fanti', value: 'fat' },
	{ label: 'Faroese', value: 'fo' },
	{ label: 'Fiji Hindi', value: 'hif' },
	{ label: 'Fijian', value: 'fj' },
	{ label: 'Filipino', value: 'fil' },
	{ label: 'Finnish', value: 'fi' },
	{ label: 'Flemish', value: 'nl_BE' },
	{ label: 'Fon', value: 'fon' },
	{ label: 'Frafra', value: 'gur' },
	{ label: 'French', value: 'fr' },
	{ label: 'Friulian', value: 'fur' },
	{ label: 'Fulah', value: 'ff' },
	{ label: 'Ga', value: 'gaa' },
	{ label: 'Gagauz', value: 'gag' },
	{ label: 'Galician', value: 'gl' },
	{ label: 'Gan Chinese', value: 'gan' },
	{ label: 'Ganda', value: 'lg' },
	{ label: 'Gayo', value: 'gay' },
	{ label: 'Gbaya', value: 'gba' },
	{ label: 'Geez', value: 'gez' },
	{ label: 'Georgian', value: 'ka' },
	{ label: 'German', value: 'de' },
	{ label: 'Gheg Albanian', value: 'aln' },
	{ label: 'Ghomala', value: 'bbj' },
	{ label: 'Gilaki', value: 'glk' },
	{ label: 'Gilbertese', value: 'gil' },
	{ label: 'Goan Konkani', value: 'gom' },
	{ label: 'Gondi', value: 'gon' },
	{ label: 'Gorontalo', value: 'gor' },
	{ label: 'Gothic', value: 'got' },
	{ label: 'Grebo', value: 'grb' },
	{ label: 'Greek', value: 'el' },
	{ label: 'Guarani', value: 'gn' },
	{ label: 'Gujarati', value: 'gu' },
	{ label: 'Gusii', value: 'guz' },
	{ label: 'Gwichʼin', value: 'gwi' },
	{ label: 'Haida', value: 'hai' },
	{ label: 'Haitian', value: 'ht' },
	{ label: 'Hakka Chinese', value: 'hak' },
	{ label: 'Hausa', value: 'ha' },
	{ label: 'Hawaiian', value: 'haw' },
	{ label: 'Hebrew', value: 'he' },
	{ label: 'Herero', value: 'hz' },
	{ label: 'Hiligaynon', value: 'hil' },
	{ label: 'Hindi', value: 'hi' },
	{ label: 'Hiri Motu', value: 'ho' },
	{ label: 'Hittite', value: 'hit' },
	{ label: 'Hmong', value: 'hmn' },
	{ label: 'Hungarian', value: 'hu' },
	{ label: 'Hupa', value: 'hup' },
	{ label: 'Iban', value: 'iba' },
	{ label: 'Ibibio', value: 'ibb' },
	{ label: 'Icelandic', value: 'is' },
	{ label: 'Ido', value: 'io' },
	{ label: 'Igbo', value: 'ig' },
	{ label: 'Iloko', value: 'ilo' },
	{ label: 'Inari Sami', value: 'smn' },
	{ label: 'Indonesian', value: 'id' },
	{ label: 'Ingrian', value: 'izh' },
	{ label: 'Ingush', value: 'inh' },
	{ label: 'Interlingua', value: 'ia' },
	{ label: 'Interlingue', value: 'ie' },
	{ label: 'Inuktitut', value: 'iu' },
	{ label: 'Inupiaq', value: 'ik' },
	{ label: 'Irish', value: 'ga' },
	{ label: 'Italian', value: 'it' },
	{ label: 'Jamaican Creole English', value: 'jam' },
	{ label: 'Japanese', value: 'ja' },
	{ label: 'Javanese', value: 'jv' },
	{ label: 'Jju', value: 'kaj' },
	{ label: 'Jola-Fonyi', value: 'dyo' },
	{ label: 'Judeo-Arabic', value: 'jrb' },
	{ label: 'Judeo-Persian', value: 'jpr' },
	{ label: 'Jutish', value: 'jut' },
	{ label: 'Kabardian', value: 'kbd' },
	{ label: 'Kabuverdianu', value: 'kea' },
	{ label: 'Kabyle', value: 'kab' },
	{ label: 'Kachin', value: 'kac' },
	{ label: 'Kaingang', value: 'kgp' },
	{ label: 'Kako', value: 'kkj' },
	{ label: 'Kalaallisut', value: 'kl' },
	{ label: 'Kalenjin', value: 'kln' },
	{ label: 'Kalmyk', value: 'xal' },
	{ label: 'Kamba', value: 'kam' },
	{ label: 'Kanembu', value: 'kbl' },
	{ label: 'Kannada', value: 'kn' },
	{ label: 'Kanuri', value: 'kr' },
	{ label: 'Kara-Kalpak', value: 'kaa' },
	{ label: 'Karachay-Balkar', value: 'krc' },
	{ label: 'Karelian', value: 'krl' },
	{ label: 'Kashmiri', value: 'ks' },
	{ label: 'Kashubian', value: 'csb' },
	{ label: 'Kawi', value: 'kaw' },
	{ label: 'Kazakh', value: 'kk' },
	{ label: 'Kenyang', value: 'ken' },
	{ label: 'Khasi', value: 'kha' },
	{ label: 'Khmer', value: 'km' },
	{ label: 'Khotanese', value: 'kho' },
	{ label: 'Khowar', value: 'khw' },
	{ label: 'Kikuyu', value: 'ki' },
	{ label: 'Kimbundu', value: 'kmb' },
	{ label: 'Kinaray-a', value: 'krj' },
	{ label: 'Kinyarwanda', value: 'rw' },
	{ label: 'Kirmanjki', value: 'kiu' },
	{ label: 'Klingon', value: 'tlh' },
	{ label: 'Kom', value: 'bkm' },
	{ label: 'Komi', value: 'kv' },
	{ label: 'Komi-Permyak', value: 'koi' },
	{ label: 'Kongo', value: 'kg' },
	{ label: 'Konkani', value: 'kok' },
	{ label: 'Korean', value: 'ko' },
	{ label: 'Koro', value: 'kfo' },
	{ label: 'Kosraean', value: 'kos' },
	{ label: 'Kotava', value: 'avk' },
	{ label: 'Koyra Chiini', value: 'khq' },
	{ label: 'Koyraboro Senni', value: 'ses' },
	{ label: 'Kpelle', value: 'kpe' },
	{ label: 'Krio', value: 'kri' },
	{ label: 'Kuanyama', value: 'kj' },
	{ label: 'Kumyk', value: 'kum' },
	{ label: 'Kurdish', value: 'ku' },
	{ label: 'Kurukh', value: 'kru' },
	{ label: 'Kutenai', value: 'kut' },
	{ label: 'Kwasio', value: 'nmg' },
	{ label: 'Kyrgyz', value: 'ky' },
	{ label: 'Kʼicheʼ', value: 'quc' },
	{ label: 'Ladino', value: 'lad' },
	{ label: 'Lahnda', value: 'lah' },
	{ label: 'Lakota', value: 'lkt' },
	{ label: 'Lamba', value: 'lam' },
	{ label: 'Langi', value: 'lag' },
	{ label: 'Lao', value: 'lo' },
	{ label: 'Latgalian', value: 'ltg' },
	{ label: 'Latin', value: 'la' },
	{ label: 'Latin American Spanish', value: 'es_419' },
	{ label: 'Latvian', value: 'lv' },
	{ label: 'Laz', value: 'lzz' },
	{ label: 'Lezghian', value: 'lez' },
	{ label: 'Ligurian', value: 'lij' },
	{ label: 'Limburgish', value: 'li' },
	{ label: 'Lingala', value: 'ln' },
	{ label: 'Lingua Franca Nova', value: 'lfn' },
	{ label: 'Literary Chinese', value: 'lzh' },
	{ label: 'Lithuanian', value: 'lt' },
	{ label: 'Livonian', value: 'liv' },
	{ label: 'Lojban', value: 'jbo' },
	{ label: 'Lombard', value: 'lmo' },
	{ label: 'Low German', value: 'nds' },
	{ label: 'Lower Silesian', value: 'sli' },
	{ label: 'Lower Sorbian', value: 'dsb' },
	{ label: 'Lozi', value: 'loz' },
	{ label: 'Luba-Katanga', value: 'lu' },
	{ label: 'Luba-Lulua', value: 'lua' },
	{ label: 'Luiseno', value: 'lui' },
	{ label: 'Lule Sami', value: 'smj' },
	{ label: 'Lunda', value: 'lun' },
	{ label: 'Luo', value: 'luo' },
	{ label: 'Luxembourgish', value: 'lb' },
	{ label: 'Luyia', value: 'luy' },
	{ label: 'Maba', value: 'mde' },
	{ label: 'Macedonian', value: 'mk' },
	{ label: 'Machame', value: 'jmc' },
	{ label: 'Madurese', value: 'mad' },
	{ label: 'Mafa', value: 'maf' },
	{ label: 'Magahi', value: 'mag' },
	{ label: 'Main-Franconian', value: 'vmf' },
	{ label: 'Maithili', value: 'mai' },
	{ label: 'Makasar', value: 'mak' },
	{ label: 'Makhuwa-Meetto', value: 'mgh' },
	{ label: 'Makonde', value: 'kde' },
	{ label: 'Malagasy', value: 'mg' },
	{ label: 'Malay', value: 'ms' },
	{ label: 'Malayalam', value: 'ml' },
	{ label: 'Maltese', value: 'mt' },
	{ label: 'Manchu', value: 'mnc' },
	{ label: 'Mandar', value: 'mdr' },
	{ label: 'Mandingo', value: 'man' },
	{ label: 'Manipuri', value: 'mni' },
	{ label: 'Manx', value: 'gv' },
	{ label: 'Maori', value: 'mi' },
	{ label: 'Mapuche', value: 'arn' },
	{ label: 'Marathi', value: 'mr' },
	{ label: 'Mari', value: 'chm' },
	{ label: 'Marshallese', value: 'mh' },
	{ label: 'Marwari', value: 'mwr' },
	{ label: 'Masai', value: 'mas' },
	{ label: 'Mazanderani', value: 'mzn' },
	{ label: 'Medumba', value: 'byv' },
	{ label: 'Mende', value: 'men' },
	{ label: 'Mentawai', value: 'mwv' },
	{ label: 'Meru', value: 'mer' },
	{ label: 'Metaʼ', value: 'mgo' },
	{ label: 'Mexican Spanish', value: 'es_MX' },
	{ label: 'Micmac', value: 'mic' },
	{ label: 'Middle Dutch', value: 'dum' },
	{ label: 'Middle English', value: 'enm' },
	{ label: 'Middle French', value: 'frm' },
	{ label: 'Middle High German', value: 'gmh' },
	{ label: 'Middle Irish', value: 'mga' },
	{ label: 'Min Nan Chinese', value: 'nan' },
	{ label: 'Minangkabau', value: 'min' },
	{ label: 'Mingrelian', value: 'xmf' },
	{ label: 'Mirandese', value: 'mwl' },
	{ label: 'Mizo', value: 'lus' },
	{ label: 'Modern Standard Arabic', value: 'ar_001' },
	{ label: 'Mohawk', value: 'moh' },
	{ label: 'Moksha', value: 'mdf' },
	{ label: 'Moldavian', value: 'ro_MD' },
	{ label: 'Mongo', value: 'lol' },
	{ label: 'Mongolian', value: 'mn' },
	{ label: 'Morisyen', value: 'mfe' },
	{ label: 'Moroccan Arabic', value: 'ary' },
	{ label: 'Mossi', value: 'mos' },
	{ label: 'Multiple Languages', value: 'mul' },
	{ label: 'Mundang', value: 'mua' },
	{ label: 'Muslim Tat', value: 'ttt' },
	{ label: 'Myene', value: 'mye' },
	{ label: 'Nama', value: 'naq' },
	{ label: 'Nauru', value: 'na' },
	{ label: 'Navajo', value: 'nv' },
	{ label: 'Ndonga', value: 'ng' },
	{ label: 'Neapolitan', value: 'nap' },
	{ label: 'Nepali', value: 'ne' },
	{ label: 'Newari', value: 'new' },
	{ label: 'Ngambay', value: 'sba' },
	{ label: 'Ngiemboon', value: 'nnh' },
	{ label: 'Ngomba', value: 'jgo' },
	{ label: 'Nheengatu', value: 'yrl' },
	{ label: 'Nias', value: 'nia' },
	{ label: 'Niuean', value: 'niu' },
	{ label: 'No linguistic content', value: 'zxx' },
	{ label: 'Nogai', value: 'nog' },
	{ label: 'North Ndebele', value: 'nd' },
	{ label: 'Northern Frisian', value: 'frr' },
	{ label: 'Northern Sami', value: 'se' },
	{ label: 'Northern Sotho', value: 'nso' },
	{ label: 'Norwegian', value: 'no' },
	{ label: 'Norwegian Bokmål', value: 'nb' },
	{ label: 'Norwegian Nynorsk', value: 'nn' },
	{ label: 'Novial', value: 'nov' },
	{ label: 'Nuer', value: 'nus' },
	{ label: 'Nyamwezi', value: 'nym' },
	{ label: 'Nyanja', value: 'ny' },
	{ label: 'Nyankole', value: 'nyn' },
	{ label: 'Nyasa Tonga', value: 'tog' },
	{ label: 'Nyoro', value: 'nyo' },
	{ label: 'Nzima', value: 'nzi' },
	{ label: 'NʼKo', value: 'nqo' },
	{ label: 'Occitan', value: 'oc' },
	{ label: 'Ojibwa', value: 'oj' },
	{ label: 'Old English', value: 'ang' },
	{ label: 'Old French', value: 'fro' },
	{ label: 'Old High German', value: 'goh' },
	{ label: 'Old Irish', value: 'sga' },
	{ label: 'Old Norse', value: 'non' },
	{ label: 'Old Persian', value: 'peo' },
	{ label: 'Old Provençal', value: 'pro' },
	{ label: 'Oriya', value: 'or' },
	{ label: 'Oromo', value: 'om' },
	{ label: 'Osage', value: 'osa' },
	{ label: 'Ossetic', value: 'os' },
	{ label: 'Ottoman Turkish', value: 'ota' },
	{ label: 'Pahlavi', value: 'pal' },
	{ label: 'Palatine German', value: 'pfl' },
	{ label: 'Palauan', value: 'pau' },
	{ label: 'Pali', value: 'pi' },
	{ label: 'Pampanga', value: 'pam' },
	{ label: 'Pangasinan', value: 'pag' },
	{ label: 'Papiamento', value: 'pap' },
	{ label: 'Pashto', value: 'ps' },
	{ label: 'Pennsylvania German', value: 'pdc' },
	{ label: 'Persian', value: 'fa' },
	{ label: 'Phoenician', value: 'phn' },
	{ label: 'Picard', value: 'pcd' },
	{ label: 'Piedmontese', value: 'pms' },
	{ label: 'Plautdietsch', value: 'pdt' },
	{ label: 'Pohnpeian', value: 'pon' },
	{ label: 'Polish', value: 'pl' },
	{ label: 'Pontic', value: 'pnt' },
	{ label: 'Portuguese', value: 'pt' },
	{ label: 'Prussian', value: 'prg' },
	{ label: 'Punjabi', value: 'pa' },
	{ label: 'Quechua', value: 'qu' },
	{ label: 'Rajasthani', value: 'raj' },
	{ label: 'Rapanui', value: 'rap' },
	{ label: 'Rarotongan', value: 'rar' },
	{ label: 'Riffian', value: 'rif' },
	{ label: 'Romagnol', value: 'rgn' },
	{ label: 'Romanian', value: 'ro' },
	{ label: 'Romansh', value: 'rm' },
	{ label: 'Romany', value: 'rom' },
	{ label: 'Rombo', value: 'rof' },
	{ label: 'Root', value: 'root' },
	{ label: 'Rotuman', value: 'rtm' },
	{ label: 'Roviana', value: 'rug' },
	{ label: 'Rundi', value: 'rn' },
	{ label: 'Russian', value: 'ru' },
	{ label: 'Rusyn', value: 'rue' },
	{ label: 'Rwa', value: 'rwk' },
	{ label: 'Saho', value: 'ssy' },
	{ label: 'Sakha', value: 'sah' },
	{ label: 'Samaritan Aramaic', value: 'sam' },
	{ label: 'Samburu', value: 'saq' },
	{ label: 'Samoan', value: 'sm' },
	{ label: 'Samogitian', value: 'sgs' },
	{ label: 'Sandawe', value: 'sad' },
	{ label: 'Sango', value: 'sg' },
	{ label: 'Sangu', value: 'sbp' },
	{ label: 'Sanskrit', value: 'sa' },
	{ label: 'Santali', value: 'sat' },
	{ label: 'Sardinian', value: 'sc' },
	{ label: 'Sasak', value: 'sas' },
	{ label: 'Sassarese Sardinian', value: 'sdc' },
	{ label: 'Saterland Frisian', value: 'stq' },
	{ label: 'Saurashtra', value: 'saz' },
	{ label: 'Scots', value: 'sco' },
	{ label: 'Scottish Gaelic', value: 'gd' },
	{ label: 'Selayar', value: 'sly' },
	{ label: 'Selkup', value: 'sel' },
	{ label: 'Sena', value: 'seh' },
	{ label: 'Seneca', value: 'see' },
	{ label: 'Serbian', value: 'sr' },
	{ label: 'Serbo-Croatian', value: 'sh' },
	{ label: 'Serer', value: 'srr' },
	{ label: 'Seri', value: 'sei' },
	{ label: 'Shambala', value: 'ksb' },
	{ label: 'Shan', value: 'shn' },
	{ label: 'Shona', value: 'sn' },
	{ label: 'Sichuan Yi', value: 'ii' },
	{ label: 'Sicilian', value: 'scn' },
	{ label: 'Sidamo', value: 'sid' },
	{ label: 'Siksika', value: 'bla' },
	{ label: 'Silesian', value: 'szl' },
	{ label: 'Simplified Chinese', value: 'zh_Hans' },
	{ label: 'Sindhi', value: 'sd' },
	{ label: 'Sinhala', value: 'si' },
	{ label: 'Skolt Sami', value: 'sms' },
	{ label: 'Slave', value: 'den' },
	{ label: 'Slovak', value: 'sk' },
	{ label: 'Slovenian', value: 'sl' },
	{ label: 'Soga', value: 'xog' },
	{ label: 'Sogdien', value: 'sog' },
	{ label: 'Somali', value: 'so' },
	{ label: 'Soninke', value: 'snk' },
	{ label: 'South Azerbaijani', value: 'azb' },
	{ label: 'South Ndebele', value: 'nr' },
	{ label: 'Southern Altai', value: 'alt' },
	{ label: 'Southern Sami', value: 'sma' },
	{ label: 'Southern Sotho', value: 'st' },
	{ label: 'Spanish', value: 'es' },
	{ label: 'Sranan Tongo', value: 'srn' },
	{ label: 'Standard Moroccan Tamazight', value: 'zgh' },
	{ label: 'Sukuma', value: 'suk' },
	{ label: 'Sumerian', value: 'sux' },
	{ label: 'Sundanese', value: 'su' },
	{ label: 'Susu', value: 'sus' },
	{ label: 'Swahili', value: 'sw' },
	{ label: 'Swati', value: 'ss' },
	{ label: 'Swedish', value: 'sv' },
	{ label: 'Swiss French', value: 'fr_CH' },
	{ label: 'Swiss German', value: 'gsw' },
	{ label: 'Swiss High German', value: 'de_CH' },
	{ label: 'Syriac', value: 'syr' },
	{ label: 'Tachelhit', value: 'shi' },
	{ label: 'Tagalog', value: 'tl' },
	{ label: 'Tahitian', value: 'ty' },
	{ label: 'Taita', value: 'dav' },
	{ label: 'Tajik', value: 'tg' },
	{ label: 'Talysh', value: 'tly' },
	{ label: 'Tamashek', value: 'tmh' },
	{ label: 'Tamil', value: 'ta' },
	{ label: 'Taroko', value: 'trv' },
	{ label: 'Tasawaq', value: 'twq' },
	{ label: 'Tatar', value: 'tt' },
	{ label: 'Telugu', value: 'te' },
	{ label: 'Tereno', value: 'ter' },
	{ label: 'Teso', value: 'teo' },
	{ label: 'Tetum', value: 'tet' },
	{ label: 'Thai', value: 'th' },
	{ label: 'Tibetan', value: 'bo' },
	{ label: 'Tigre', value: 'tig' },
	{ label: 'Tigrinya', value: 'ti' },
	{ label: 'Timne', value: 'tem' },
	{ label: 'Tiv', value: 'tiv' },
	{ label: 'Tlingit', value: 'tli' },
	{ label: 'Tok Pisin', value: 'tpi' },
	{ label: 'Tokelau', value: 'tkl' },
	{ label: 'Tongan', value: 'to' },
	{ label: 'Tornedalen Finnish', value: 'fit' },
	{ label: 'Traditional Chinese', value: 'zh_Hant' },
	{ label: 'Tsakhur', value: 'tkr' },
	{ label: 'Tsakonian', value: 'tsd' },
	{ label: 'Tsimshian', value: 'tsi' },
	{ label: 'Tsonga', value: 'ts' },
	{ label: 'Tswana', value: 'tn' },
	{ label: 'Tulu', value: 'tcy' },
	{ label: 'Tumbuka', value: 'tum' },
	{ label: 'Tunisian Arabic', value: 'aeb' },
	{ label: 'Turkish', value: 'tr' },
	{ label: 'Turkmen', value: 'tk' },
	{ label: 'Turoyo', value: 'tru' },
	{ label: 'Tuvalu', value: 'tvl' },
	{ label: 'Tuvinian', value: 'tyv' },
	{ label: 'Twi', value: 'tw' },
	{ label: 'Tyap', value: 'kcg' },
	{ label: 'Udmurt', value: 'udm' },
	{ label: 'Ugaritic', value: 'uga' },
	{ label: 'Ukrainian', value: 'uk' },
	{ label: 'Umbundu', value: 'umb' },
	{ label: 'Unknown Language', value: 'und' },
	{ label: 'Upper Sorbian', value: 'hsb' },
	{ label: 'Urdu', value: 'ur' },
	{ label: 'Uyghur', value: 'ug' },
	{ label: 'Uzbek', value: 'uz' },
	{ label: 'Vai', value: 'vai' },
	{ label: 'Venda', value: 've' },
	{ label: 'Venetian', value: 'vec' },
	{ label: 'Veps', value: 'vep' },
	{ label: 'Vietnamese', value: 'vi' },
	{ label: 'Volapük', value: 'vo' },
	{ label: 'Võro', value: 'vro' },
	{ label: 'Votic', value: 'vot' },
	{ label: 'Vunjo', value: 'vun' },
	{ label: 'Walloon', value: 'wa' },
	{ label: 'Walser', value: 'wae' },
	{ label: 'Waray', value: 'war' },
	{ label: 'Warlpiri', value: 'wbp' },
	{ label: 'Washo', value: 'was' },
	{ label: 'Wayuu', value: 'guc' },
	{ label: 'Welsh', value: 'cy' },
	{ label: 'West Flemish', value: 'vls' },
	{ label: 'Western Frisian', value: 'fy' },
	{ label: 'Western Mari', value: 'mrj' },
	{ label: 'Wolaytta', value: 'wal' },
	{ label: 'Wolof', value: 'wo' },
	{ label: 'Wu Chinese', value: 'wuu' },
	{ label: 'Xhosa', value: 'xh' },
	{ label: 'Xiang Chinese', value: 'hsn' },
	{ label: 'Yangben', value: 'yav' },
	{ label: 'Yao', value: 'yao' },
	{ label: 'Yapese', value: 'yap' },
	{ label: 'Yemba', value: 'ybb' },
	{ label: 'Yiddish', value: 'yi' },
	{ label: 'Yoruba', value: 'yo' },
	{ label: 'Zapotec', value: 'zap' },
	{ label: 'Zarma', value: 'dje' },
	{ label: 'Zaza', value: 'zza' },
	{ label: 'Zeelandic', value: 'zea' },
	{ label: 'Zenaga', value: 'zen' },
	{ label: 'Zhuang', value: 'za' },
	{ label: 'Zoroastrian Dari', value: 'gbz' },
	{ label: 'Zulu', value: 'zu' },
	{ label: 'Zuni', value: 'zun' },
]

export default languageCodes

/*
export const allLangs = {
	ab: 'Abkhazian',
	ace: 'Achinese',
	ach: 'Acoli',
	ada: 'Adangme',
	ady: 'Adyghe',
	aa: 'Afar',
	afh: 'Afrihili',
	af: 'Afrikaans',
	agq: 'Aghem',
	ain: 'Ainu',
	ak: 'Akan',
	akk: 'Akkadian',
	bss: 'Akoose',
	akz: 'Alabama',
	sq: 'Albanian',
	ale: 'Aleut',
	arq: 'Algerian Arabic',
	en_US: 'American English',
	ase: 'American Sign Language',
	am: 'Amharic',
	egy: 'Ancient Egyptian',
	grc: 'Ancient Greek',
	anp: 'Angika',
	njo: 'Ao Naga',
	ar: 'Arabic',
	an: 'Aragonese',
	arc: 'Aramaic',
	aro: 'Araona',
	arp: 'Arapaho',
	arw: 'Arawak',
	hy: 'Armenian',
	rup: 'Aromanian',
	frp: 'Arpitan',
	as: 'Assamese',
	ast: 'Asturian',
	asa: 'Asu',
	cch: 'Atsam',
	en_AU: 'Australian English',
	de_AT: 'Austrian German',
	av: 'Avaric',
	ae: 'Avestan',
	awa: 'Awadhi',
	ay: 'Aymara',
	az: 'Azerbaijani',
	bfq: 'Badaga',
	ksf: 'Bafia',
	bfd: 'Bafut',
	bqi: 'Bakhtiari',
	ban: 'Balinese',
	bal: 'Baluchi',
	bm: 'Bambara',
	bax: 'Bamun',
	bjn: 'Banjar',
	bas: 'Basaa',
	ba: 'Bashkir',
	eu: 'Basque',
	bbc: 'Batak Toba',
	bar: 'Bavarian',
	bej: 'Beja',
	be: 'Belarusian',
	bem: 'Bemba',
	bez: 'Bena',
	bn: 'Bengali',
	bew: 'Betawi',
	bho: 'Bhojpuri',
	bik: 'Bikol',
	bin: 'Bini',
	bpy: 'Bishnupriya',
	bi: 'Bislama',
	byn: 'Blin',
	zbl: 'Blissymbols',
	brx: 'Bodo',
	bs: 'Bosnian',
	brh: 'Brahui',
	bra: 'Braj',
	pt_BR: 'Brazilian Portuguese',
	br: 'Breton',
	en_GB: 'British English',
	bug: 'Buginese',
	bg: 'Bulgarian',
	bum: 'Bulu',
	bua: 'Buriat',
	my: 'Burmese',
	cad: 'Caddo',
	frc: 'Cajun French',
	en_CA: 'Canadian English',
	fr_CA: 'Canadian French',
	yue: 'Cantonese',
	cps: 'Capiznon',
	car: 'Carib',
	ca: 'Catalan',
	cay: 'Cayuga',
	ceb: 'Cebuano',
	tzm: 'Central Atlas Tamazight',
	dtp: 'Central Dusun',
	ckb: 'Central Kurdish',
	esu: 'Central Yupik',
	shu: 'Chadian Arabic',
	chg: 'Chagatai',
	ch: 'Chamorro',
	ce: 'Chechen',
	chr: 'Cherokee',
	chy: 'Cheyenne',
	chb: 'Chibcha',
	cgg: 'Chiga',
	qug: 'Chimborazo Highland Quichua',
	zh: 'Chinese',
	chn: 'Chinook Jargon',
	chp: 'Chipewyan',
	cho: 'Choctaw',
	cu: 'Church Slavic',
	chk: 'Chuukese',
	cv: 'Chuvash',
	nwc: 'Classical Newari',
	syc: 'Classical Syriac',
	ksh: 'Colognian',
	swb: 'Comorian',
	swc: 'Congo Swahili',
	cop: 'Coptic',
	kw: 'Cornish',
	co: 'Corsican',
	cr: 'Cree',
	mus: 'Creek',
	crh: 'Crimean Turkish',
	hr: 'Croatian',
	cs: 'Czech',
	dak: 'Dakota',
	da: 'Danish',
	dar: 'Dargwa',
	dzg: 'Dazaga',
	del: 'Delaware',
	din: 'Dinka',
	dv: 'Divehi',
	doi: 'Dogri',
	dgr: 'Dogrib',
	dua: 'Duala',
	nl: 'Dutch',
	dyu: 'Dyula',
	dz: 'Dzongkha',
	frs: 'Eastern Frisian',
	efi: 'Efik',
	arz: 'Egyptian Arabic',
	eka: 'Ekajuk',
	elx: 'Elamite',
	ebu: 'Embu',
	egl: 'Emilian',
	en: 'English',
	myv: 'Erzya',
	eo: 'Esperanto',
	et: 'Estonian',
	pt_PT: 'European Portuguese',
	es_ES: 'European Spanish',
	ee: 'Ewe',
	ewo: 'Ewondo',
	ext: 'Extremaduran',
	fan: 'Fang',
	fat: 'Fanti',
	fo: 'Faroese',
	hif: 'Fiji Hindi',
	fj: 'Fijian',
	fil: 'Filipino',
	fi: 'Finnish',
	nl_BE: 'Flemish',
	fon: 'Fon',
	gur: 'Frafra',
	fr: 'French',
	fur: 'Friulian',
	ff: 'Fulah',
	gaa: 'Ga',
	gag: 'Gagauz',
	gl: 'Galician',
	gan: 'Gan Chinese',
	lg: 'Ganda',
	gay: 'Gayo',
	gba: 'Gbaya',
	gez: 'Geez',
	ka: 'Georgian',
	de: 'German',
	aln: 'Gheg Albanian',
	bbj: 'Ghomala',
	glk: 'Gilaki',
	gil: 'Gilbertese',
	gom: 'Goan Konkani',
	gon: 'Gondi',
	gor: 'Gorontalo',
	got: 'Gothic',
	grb: 'Grebo',
	el: 'Greek',
	gn: 'Guarani',
	gu: 'Gujarati',
	guz: 'Gusii',
	gwi: 'Gwich\u02bcin',
	hai: 'Haida',
	ht: 'Haitian',
	hak: 'Hakka Chinese',
	ha: 'Hausa',
	haw: 'Hawaiian',
	he: 'Hebrew',
	hz: 'Herero',
	hil: 'Hiligaynon',
	hi: 'Hindi',
	ho: 'Hiri Motu',
	hit: 'Hittite',
	hmn: 'Hmong',
	hu: 'Hungarian',
	hup: 'Hupa',
	iba: 'Iban',
	ibb: 'Ibibio',
	is: 'Icelandic',
	io: 'Ido',
	ig: 'Igbo',
	ilo: 'Iloko',
	smn: 'Inari Sami',
	id: 'Indonesian',
	izh: 'Ingrian',
	inh: 'Ingush',
	ia: 'Interlingua',
	ie: 'Interlingue',
	iu: 'Inuktitut',
	ik: 'Inupiaq',
	ga: 'Irish',
	it: 'Italian',
	jam: 'Jamaican Creole English',
	ja: 'Japanese',
	jv: 'Javanese',
	kaj: 'Jju',
	dyo: 'Jola-Fonyi',
	jrb: 'Judeo-Arabic',
	jpr: 'Judeo-Persian',
	jut: 'Jutish',
	kbd: 'Kabardian',
	kea: 'Kabuverdianu',
	kab: 'Kabyle',
	kac: 'Kachin',
	kgp: 'Kaingang',
	kkj: 'Kako',
	kl: 'Kalaallisut',
	kln: 'Kalenjin',
	xal: 'Kalmyk',
	kam: 'Kamba',
	kbl: 'Kanembu',
	kn: 'Kannada',
	kr: 'Kanuri',
	kaa: 'Kara-Kalpak',
	krc: 'Karachay-Balkar',
	krl: 'Karelian',
	ks: 'Kashmiri',
	csb: 'Kashubian',
	kaw: 'Kawi',
	kk: 'Kazakh',
	ken: 'Kenyang',
	kha: 'Khasi',
	km: 'Khmer',
	kho: 'Khotanese',
	khw: 'Khowar',
	ki: 'Kikuyu',
	kmb: 'Kimbundu',
	krj: 'Kinaray-a',
	rw: 'Kinyarwanda',
	kiu: 'Kirmanjki',
	tlh: 'Klingon',
	bkm: 'Kom',
	kv: 'Komi',
	koi: 'Komi-Permyak',
	kg: 'Kongo',
	kok: 'Konkani',
	ko: 'Korean',
	kfo: 'Koro',
	kos: 'Kosraean',
	avk: 'Kotava',
	khq: 'Koyra Chiini',
	ses: 'Koyraboro Senni',
	kpe: 'Kpelle',
	kri: 'Krio',
	kj: 'Kuanyama',
	kum: 'Kumyk',
	ku: 'Kurdish',
	kru: 'Kurukh',
	kut: 'Kutenai',
	nmg: 'Kwasio',
	ky: 'Kyrgyz',
	quc: 'K\u02bciche\u02bc',
	lad: 'Ladino',
	lah: 'Lahnda',
	lkt: 'Lakota',
	lam: 'Lamba',
	lag: 'Langi',
	lo: 'Lao',
	ltg: 'Latgalian',
	la: 'Latin',
	es_419: 'Latin American Spanish',
	lv: 'Latvian',
	lzz: 'Laz',
	lez: 'Lezghian',
	lij: 'Ligurian',
	li: 'Limburgish',
	ln: 'Lingala',
	lfn: 'Lingua Franca Nova',
	lzh: 'Literary Chinese',
	lt: 'Lithuanian',
	liv: 'Livonian',
	jbo: 'Lojban',
	lmo: 'Lombard',
	nds: 'Low German',
	sli: 'Lower Silesian',
	dsb: 'Lower Sorbian',
	loz: 'Lozi',
	lu: 'Luba-Katanga',
	lua: 'Luba-Lulua',
	lui: 'Luiseno',
	smj: 'Lule Sami',
	lun: 'Lunda',
	luo: 'Luo',
	lb: 'Luxembourgish',
	luy: 'Luyia',
	mde: 'Maba',
	mk: 'Macedonian',
	jmc: 'Machame',
	mad: 'Madurese',
	maf: 'Mafa',
	mag: 'Magahi',
	vmf: 'Main-Franconian',
	mai: 'Maithili',
	mak: 'Makasar',
	mgh: 'Makhuwa-Meetto',
	kde: 'Makonde',
	mg: 'Malagasy',
	ms: 'Malay',
	ml: 'Malayalam',
	mt: 'Maltese',
	mnc: 'Manchu',
	mdr: 'Mandar',
	man: 'Mandingo',
	mni: 'Manipuri',
	gv: 'Manx',
	mi: 'Maori',
	arn: 'Mapuche',
	mr: 'Marathi',
	chm: 'Mari',
	mh: 'Marshallese',
	mwr: 'Marwari',
	mas: 'Masai',
	mzn: 'Mazanderani',
	byv: 'Medumba',
	men: 'Mende',
	mwv: 'Mentawai',
	mer: 'Meru',
	mgo: 'Meta\u02bc',
	es_MX: 'Mexican Spanish',
	mic: 'Micmac',
	dum: 'Middle Dutch',
	enm: 'Middle English',
	frm: 'Middle French',
	gmh: 'Middle High German',
	mga: 'Middle Irish',
	nan: 'Min Nan Chinese',
	min: 'Minangkabau',
	xmf: 'Mingrelian',
	mwl: 'Mirandese',
	lus: 'Mizo',
	ar_001: 'Modern Standard Arabic',
	moh: 'Mohawk',
	mdf: 'Moksha',
	ro_MD: 'Moldavian',
	lol: 'Mongo',
	mn: 'Mongolian',
	mfe: 'Morisyen',
	ary: 'Moroccan Arabic',
	mos: 'Mossi',
	mul: 'Multiple Languages',
	mua: 'Mundang',
	ttt: 'Muslim Tat',
	mye: 'Myene',
	naq: 'Nama',
	na: 'Nauru',
	nv: 'Navajo',
	ng: 'Ndonga',
	nap: 'Neapolitan',
	ne: 'Nepali',
	new: 'Newari',
	sba: 'Ngambay',
	nnh: 'Ngiemboon',
	jgo: 'Ngomba',
	yrl: 'Nheengatu',
	nia: 'Nias',
	niu: 'Niuean',
	zxx: 'No linguistic content',
	nog: 'Nogai',
	nd: 'North Ndebele',
	frr: 'Northern Frisian',
	se: 'Northern Sami',
	nso: 'Northern Sotho',
	no: 'Norwegian',
	nb: 'Norwegian Bokm\u00e5l',
	nn: 'Norwegian Nynorsk',
	nov: 'Novial',
	nus: 'Nuer',
	nym: 'Nyamwezi',
	ny: 'Nyanja',
	nyn: 'Nyankole',
	tog: 'Nyasa Tonga',
	nyo: 'Nyoro',
	nzi: 'Nzima',
	nqo: 'N\u02bcKo',
	oc: 'Occitan',
	oj: 'Ojibwa',
	ang: 'Old English',
	fro: 'Old French',
	goh: 'Old High German',
	sga: 'Old Irish',
	non: 'Old Norse',
	peo: 'Old Persian',
	pro: 'Old Proven\u00e7al',
	or: 'Oriya',
	om: 'Oromo',
	osa: 'Osage',
	os: 'Ossetic',
	ota: 'Ottoman Turkish',
	pal: 'Pahlavi',
	pfl: 'Palatine German',
	pau: 'Palauan',
	pi: 'Pali',
	pam: 'Pampanga',
	pag: 'Pangasinan',
	pap: 'Papiamento',
	ps: 'Pashto',
	pdc: 'Pennsylvania German',
	fa: 'Persian',
	phn: 'Phoenician',
	pcd: 'Picard',
	pms: 'Piedmontese',
	pdt: 'Plautdietsch',
	pon: 'Pohnpeian',
	pl: 'Polish',
	pnt: 'Pontic',
	pt: 'Portuguese',
	prg: 'Prussian',
	pa: 'Punjabi',
	qu: 'Quechua',
	raj: 'Rajasthani',
	rap: 'Rapanui',
	rar: 'Rarotongan',
	rif: 'Riffian',
	rgn: 'Romagnol',
	ro: 'Romanian',
	rm: 'Romansh',
	rom: 'Romany',
	rof: 'Rombo',
	root: 'Root',
	rtm: 'Rotuman',
	rug: 'Roviana',
	rn: 'Rundi',
	ru: 'Russian',
	rue: 'Rusyn',
	rwk: 'Rwa',
	ssy: 'Saho',
	sah: 'Sakha',
	sam: 'Samaritan Aramaic',
	saq: 'Samburu',
	sm: 'Samoan',
	sgs: 'Samogitian',
	sad: 'Sandawe',
	sg: 'Sango',
	sbp: 'Sangu',
	sa: 'Sanskrit',
	sat: 'Santali',
	sc: 'Sardinian',
	sas: 'Sasak',
	sdc: 'Sassarese Sardinian',
	stq: 'Saterland Frisian',
	saz: 'Saurashtra',
	sco: 'Scots',
	gd: 'Scottish Gaelic',
	sly: 'Selayar',
	sel: 'Selkup',
	seh: 'Sena',
	see: 'Seneca',
	sr: 'Serbian',
	sh: 'Serbo-Croatian',
	srr: 'Serer',
	sei: 'Seri',
	ksb: 'Shambala',
	shn: 'Shan',
	sn: 'Shona',
	ii: 'Sichuan Yi',
	scn: 'Sicilian',
	sid: 'Sidamo',
	bla: 'Siksika',
	szl: 'Silesian',
	zh_Hans: 'Simplified Chinese',
	sd: 'Sindhi',
	si: 'Sinhala',
	sms: 'Skolt Sami',
	den: 'Slave',
	sk: 'Slovak',
	sl: 'Slovenian',
	xog: 'Soga',
	sog: 'Sogdien',
	so: 'Somali',
	snk: 'Soninke',
	azb: 'South Azerbaijani',
	nr: 'South Ndebele',
	alt: 'Southern Altai',
	sma: 'Southern Sami',
	st: 'Southern Sotho',
	es: 'Spanish',
	srn: 'Sranan Tongo',
	zgh: 'Standard Moroccan Tamazight',
	suk: 'Sukuma',
	sux: 'Sumerian',
	su: 'Sundanese',
	sus: 'Susu',
	sw: 'Swahili',
	ss: 'Swati',
	sv: 'Swedish',
	fr_CH: 'Swiss French',
	gsw: 'Swiss German',
	de_CH: 'Swiss High German',
	syr: 'Syriac',
	shi: 'Tachelhit',
	tl: 'Tagalog',
	ty: 'Tahitian',
	dav: 'Taita',
	tg: 'Tajik',
	tly: 'Talysh',
	tmh: 'Tamashek',
	ta: 'Tamil',
	trv: 'Taroko',
	twq: 'Tasawaq',
	tt: 'Tatar',
	te: 'Telugu',
	ter: 'Tereno',
	teo: 'Teso',
	tet: 'Tetum',
	th: 'Thai',
	bo: 'Tibetan',
	tig: 'Tigre',
	ti: 'Tigrinya',
	tem: 'Timne',
	tiv: 'Tiv',
	tli: 'Tlingit',
	tpi: 'Tok Pisin',
	tkl: 'Tokelau',
	to: 'Tongan',
	fit: 'Tornedalen Finnish',
	zh_Hant: 'Traditional Chinese',
	tkr: 'Tsakhur',
	tsd: 'Tsakonian',
	tsi: 'Tsimshian',
	ts: 'Tsonga',
	tn: 'Tswana',
	tcy: 'Tulu',
	tum: 'Tumbuka',
	aeb: 'Tunisian Arabic',
	tr: 'Turkish',
	tk: 'Turkmen',
	tru: 'Turoyo',
	tvl: 'Tuvalu',
	tyv: 'Tuvinian',
	tw: 'Twi',
	kcg: 'Tyap',
	udm: 'Udmurt',
	uga: 'Ugaritic',
	uk: 'Ukrainian',
	umb: 'Umbundu',
	und: 'Unknown Language',
	hsb: 'Upper Sorbian',
	ur: 'Urdu',
	ug: 'Uyghur',
	uz: 'Uzbek',
	vai: 'Vai',
	ve: 'Venda',
	vec: 'Venetian',
	vep: 'Veps',
	vi: 'Vietnamese',
	vo: 'Volap\u00fck',
	vro: 'V\u00f5ro',
	vot: 'Votic',
	vun: 'Vunjo',
	wa: 'Walloon',
	wae: 'Walser',
	war: 'Waray',
	wbp: 'Warlpiri',
	was: 'Washo',
	guc: 'Wayuu',
	cy: 'Welsh',
	vls: 'West Flemish',
	fy: 'Western Frisian',
	mrj: 'Western Mari',
	wal: 'Wolaytta',
	wo: 'Wolof',
	wuu: 'Wu Chinese',
	xh: 'Xhosa',
	hsn: 'Xiang Chinese',
	yav: 'Yangben',
	yao: 'Yao',
	yap: 'Yapese',
	ybb: 'Yemba',
	yi: 'Yiddish',
	yo: 'Yoruba',
	zap: 'Zapotec',
	dje: 'Zarma',
	zza: 'Zaza',
	zea: 'Zeelandic',
	zen: 'Zenaga',
	za: 'Zhuang',
	gbz: 'Zoroastrian Dari',
	zu: 'Zulu',
	zun: 'Zuni',
}
*/
